Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,14 +19,19 @@ jobs:
         with:
           python-version: '3.10'
 
-      - name: Install System Dependencies & Buildozer
+      - name: Install System Dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
-          pip install --upgrade buildozer cython virtualenv
+          # Fixed Cython version to avoid compatibility issues
+          pip install --upgrade Cython==0.29.33 virtualenv buildozer
 
-      - name: Build APK with Buildozer
-        run: buildozer android debug
+      - name: Build APK with Buildozer (With Auto-Retry)
+        run: |
+          # Agar Google server 500 error de toh yeh code 3 dafa khud try karega
+          for i in {1..3}; do
+            buildozer android debug && break || echo "Download failed due to server error, retrying in 10 seconds..." && sleep 10;
+          done
 
       - name: Upload APK Artifact
         uses: actions/upload-artifact@v4
